#!/usr/bin/env python3
"""Generate a synthetic substrate with the real one's *shape*, for benchmarking.

The NFR register carries thirty-one targets and, until now, zero measurements.
Nothing in this project has ever run above 276 entities, while NFR-008 promises
Phase 5 volumetrics — 10⁵ entities and 10⁶ claims — "without architectural
change". That is a claim about software nobody has tested, and the substrate is
loaded wholly into memory from every file under a root, so it is exactly the
kind of claim that fails at one order of magnitude and not before.

**Nothing generated here is biology.** Every record is namespaced `SYN:` and
carries a provenance line saying so, and the generator refuses to write into a
directory holding real content. Synthetic anatomy leaking into the canonical
substrate would be the single worst failure this project could have — it is the
fabrication the whole evidence apparatus exists to prevent — so the guard is
structural rather than a convention, and `tests/test_synth.py` asserts no `SYN:`
id is reachable from `ontology/`.

What is copied from the real substrate is its *shape*, measured rather than
guessed (`--shape ontology/` re-measures):

    entities 276 · claims/entity 1.53 · relationships/entity 0.74
    synonyms/entity 1.8 · multi-membership 5% of organs
    levels: L2 and L3 hold 90% of entities, the tail runs to L9

Usage:
    python3 tools/synth.py <out-dir> --entities 10000
    python3 tools/synth.py <out-dir> --entities 100000 --claims-per-entity 10
"""
from __future__ import annotations

import argparse
import json
import os
import random
import sys

# The proportion of entities at each level, measured from ontology/ and rounded.
# L2 is heavy because the narrative seed lives there; L3 is heavy because organs
# are what an anatomical reference mostly holds. Keeping the real skew matters:
# a uniform distribution would produce a shallow tree and flatter traversals
# than anything the real model will ever have.
LEVEL_MIX = ((2, 0.46), (3, 0.38), (4, 0.05), (5, 0.04),
             (6, 0.03), (7, 0.02), (8, 0.01), (9, 0.01))

CLASS_AT_LEVEL = {0: 'Organism', 1: 'Region', 2: 'System', 3: 'Organ',
                  4: 'TissueType', 5: 'TissueType', 6: 'CellPopulation',
                  7: 'CellType', 8: 'Organelle', 9: 'Biomolecule'}

MODE_AT_LEVEL = {0: 'enumerated', 1: 'enumerated', 2: 'enumerated',
                 3: 'enumerated', 4: 'typed', 5: 'typed', 6: 'statistical',
                 7: 'typed', 8: 'typed', 9: 'typed'}

REGIONS = 9
SYSTEMS = 12
MULTI_MEMBERSHIP_RATE = 0.14      # organs belonging to more than one system
FINDING_RATE = 0.03               # claims that are findings, not definitions

SYNTHETIC_NOTE = (
    'SYNTHETIC BENCHMARK RECORD — generated by tools/synth.py to measure the '
    'NFR register at volume. This is not biology, was not reviewed, and must '
    'never enter the canonical substrate.')


def _entity(eid: str, level: int, subsystem: str, parent: str | None,
            rng: random.Random, synonyms: int) -> dict:
    return {
        'id': eid,
        'minted': True,
        'entity_class': CLASS_AT_LEVEL[level],
        'level': level,
        'subsystem': subsystem,
        'preferred_term': f'synthetic structure {eid.split(":")[-1]}',
        'compilation_status': 'structured',
        'representation_mode': MODE_AT_LEVEL[level],
        'review_state': 'provisional',
        'admitted_by': 'agent:synthetic',
        'provenance_source': SYNTHETIC_NOTE,
        'xrefs': [],
        'synonyms': [{'term': f'syn-{eid.split(":")[-1]}-{i}',
                      'source': 'synthetic', 'register': 'exact'}
                     for i in range(synonyms)],
        'part_of': parent,
    }


def _definition_claim(cid: str, subject: str) -> dict:
    """A terminological claim, matching what the real substrate mostly holds."""
    return {
        'id': cid, 'subject': subject, 'predicate': 'has_definition',
        'object': f'A synthetic structure standing in for {subject}.',
        'kind': 'terminological', 'evidence_class': 'TRM-3',
        'authority': 'synthetic', 'definition_source': '',
        'source_type': 'generated', 'species': 'Homo sapiens',
        'population': 'not applicable', 'date_asserted': '2026-07-27',
        'review_state': 'provisional', 'assigned_by': 'agent:synthetic',
        'limitations': SYNTHETIC_NOTE,
    }


def _finding_claim(cid: str, subject: str, rng: random.Random) -> dict:
    """A biological claim on the evidence ladder, with a unit (INV-04).

    Graded EVC-5 (INFERRED) deliberately. No automated actor may assign EVC-1 or
    EVC-2 (BR-002), and grading generated numbers as MODELLED would put
    fabricated quantities two rungs above where they belong even inside a
    fixture.
    """
    return {
        'id': cid, 'subject': subject, 'predicate': 'has_quantity',
        'object': f'{rng.randint(1, 900)} mL/min',
        'kind': 'biological', 'evidence_class': 'EVC-5',
        'value': rng.randint(1, 900), 'unit': 'mL/min',
        'source': 'synthetic benchmark fixture',
        'source_type': 'generated', 'species': 'Homo sapiens',
        'population': 'adult, synthetic', 'date_asserted': '2026-07-27',
        'review_state': 'provisional', 'assigned_by': 'agent:synthetic',
        'limitations': SYNTHETIC_NOTE,
    }


def _levels_for(total: int) -> list[int]:
    """One level per entity, in the measured proportions."""
    levels: list[int] = []
    for level, share in LEVEL_MIX:
        levels.extend([level] * int(total * share))
    while len(levels) < total:
        levels.append(3)
    return levels[:total]


def generate(entities: int, claims_per_entity: float, seed: int) -> dict:
    """Build the whole synthetic substrate in memory, deterministically."""
    rng = random.Random(seed)
    ents: list[dict] = [_entity('SYN:organism', 0, 'whole-organism', None,
                                rng, 0)]
    rels: list[dict] = []
    claims: list[dict] = []

    systems = [f'system-{i:02d}' for i in range(SYSTEMS)]
    for i in range(REGIONS):
        ents.append(_entity(f'SYN:region-{i:02d}', 1, 'whole-organism',
                            'SYN:organism', rng, 1))

    # The containment spine: every entity at level L hangs off one at L-1, so
    # the tree has the real one's depth rather than a flat fan from the root.
    by_level: dict[int, list[str]] = {0: ['SYN:organism'],
                                      1: [e['id'] for e in ents[1:]]}
    remaining = entities - len(ents)
    for n, level in enumerate(_levels_for(max(remaining, 0))):
        eid = f'SYN:e{n:07d}'
        parents = by_level.get(level - 1) or by_level[1]
        parent = parents[rng.randrange(len(parents))]
        subsystem = systems[rng.randrange(SYSTEMS)]
        ents.append(_entity(eid, level, subsystem, parent, rng,
                            rng.randint(0, 3)))
        by_level.setdefault(level, []).append(eid)
        rels.append({
            'id': f'REL:{eid}-part_of', 'source': eid, 'target': parent,
            'type': 'part_of', 'compilation_status': 'structured',
            'review_state': 'provisional',
            'provenance_claim': f'CLM:{eid}-containment',
            'prose_justification': SYNTHETIC_NOTE,
        })
        claims.append({
            'id': f'CLM:{eid}-containment', 'subject': eid,
            'predicate': 'part_of', 'object': parent,
            'kind': 'terminological', 'evidence_class': 'TRM-3',
            'authority': 'synthetic', 'definition_source': '',
            'source_type': 'generated', 'species': 'Homo sapiens',
            'population': 'not applicable', 'date_asserted': '2026-07-27',
            'review_state': 'provisional', 'assigned_by': 'agent:synthetic',
            'limitations': SYNTHETIC_NOTE,
        })
        # Membership, and the multi-membership case the pancreas taught us to
        # keep in every fixture — a shape with no multi-membership organ tests
        # the single-parent path only, which is how D-019 stayed hidden.
        if level == 3:
            memberships = [subsystem]
            if rng.random() < MULTI_MEMBERSHIP_RATE:
                other = systems[rng.randrange(SYSTEMS)]
                if other != subsystem:
                    memberships.append(other)
            for m in memberships:
                rels.append({
                    'id': f'REL:{eid}-member_of-{m}', 'source': eid,
                    'target': f'SYN:{m}', 'type': 'member_of',
                    'compilation_status': 'structured',
                    'review_state': 'provisional',
                    'provenance_claim': f'CLM:{eid}-containment',
                    'prose_justification': SYNTHETIC_NOTE,
                })

    for system in systems:
        ents.append(_entity(f'SYN:{system}', 2, system, None, rng, 0))

    # Claims beyond the one containment claim each entity already carries.
    extra = max(0.0, claims_per_entity - 1.0)
    for i, entity in enumerate(ents):
        for k in range(int(extra) + (1 if rng.random() < extra % 1 else 0)):
            cid = f'CLM:{entity["id"]}-{k:02d}'
            claims.append(_finding_claim(cid, entity['id'], rng)
                          if rng.random() < FINDING_RATE
                          else _definition_claim(cid, entity['id']))

    return {'entities': ents, 'claims': claims, 'relationships': rels}


def _refuse_real_content(out_dir: str) -> None:
    """Never write into a directory that holds real records.

    The check is on content, not on the path: refusing only `ontology/` would
    be a naming convention, and this needs to be a property.
    """
    if not os.path.isdir(out_dir):
        return
    for dirpath, _, filenames in os.walk(out_dir):
        for fn in filenames:
            if not fn.endswith('.json'):
                continue
            try:
                with open(os.path.join(dirpath, fn), encoding='utf-8') as fh:
                    payload = json.load(fh)
            except (OSError, ValueError):
                continue
            rows = payload if isinstance(payload, list) else [payload]
            for row in rows:
                if isinstance(row, dict) and not str(
                        row.get('id', 'SYN:')).startswith('SYN:'):
                    raise SystemExit(
                        f'refusing to write into {out_dir}: '
                        f'{os.path.join(dirpath, fn)} holds real records '
                        f'({row.get("id")}). Synthetic content must never '
                        f'share a root with canonical content.')


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('out_dir')
    ap.add_argument('--entities', type=int, default=10_000)
    ap.add_argument('--claims-per-entity', type=float, default=1.53)
    ap.add_argument('--seed', type=int, default=20260727)
    args = ap.parse_args(argv[1:])

    _refuse_real_content(args.out_dir)
    substrate = generate(args.entities, args.claims_per_entity, args.seed)
    os.makedirs(args.out_dir, exist_ok=True)
    for name, rows in substrate.items():
        with open(os.path.join(args.out_dir, f'{name}.json'), 'w',
                  encoding='utf-8') as fh:
            json.dump(rows, fh, ensure_ascii=False)
    total = sum(len(r) for r in substrate.values())
    size = sum(os.path.getsize(os.path.join(args.out_dir, f'{n}.json'))
               for n in substrate)
    print(f'{args.out_dir}: {len(substrate["entities"])} entities, '
          f'{len(substrate["claims"])} claims, '
          f'{len(substrate["relationships"])} relationships '
          f'({total} records, {size / 1e6:.1f} MB)')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
